apiVersion: v1
kind: Secret
metadata:
  name: hpe-secret
  namespace: kube-system
stringData:
  backend: cloudvolumes.hpe.com
  protocol: "iscsi"
data:
  # echo -n "$hpecv_access_key" | base64
  username: YWRtaW4=
  # echo -n "$hpecv_access_secret" | base64
  password: YWRtaW4=
